# -*- coding: utf-8 -*-
"""Klasifikasi Gender

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IDGKzto-RObxNUM8LlknFDvR-Cr-fGhF
"""

import pandas as pd

gender = pd.read_csv('gender_classification_v7.csv')
gender.info()

gender.head(10)

#memisahkan atribut dengan label dimana X merupakan atribut dan y adalah label
X = gender[['long_hair', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide', 'nose_long', 'lips_thin', 'distance_nose_to_lip_long',]]
y = gender['gender']

#membagi dataset menjadi data latih dan data uji
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

from sklearn.tree import DecisionTreeClassifier

#buat model decision tree
tree_model = DecisionTreeClassifier()

# melatih model menggunakan data latih dengan fungsi fit
tree_model = tree_model.fit(X_train, y_train)

#evaluasi model untuk menguji sebarapa baik model yang digunakan dan akurasi yang dihasilkan
from sklearn.metrics import accuracy_score

y_pred = tree_model.predict(X_test)

accuracy_score = round(accuracy_score(y_pred, y_test), 3)

print('Accuracy', accuracy_score)

#prediksi model dengan menggunakan tree model yang sudah dibuat dalam atribut
print(tree_model.predict([[1, 1, 1, 1, 1, 1, 1]])[0])

print(tree_model.predict([[0, 12, 1, 1, 1, 0, 1]])[0])

#melihat visualisasi data dari decision tree
from sklearn.tree import export_graphviz

export_graphviz(
    tree_model,
    out_file = "Klasifikasi_gender.dot",
    feature_names=['long_hair', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide', 'nose_long', 'lips_thin', 'distance_nose_to_lip_long'],
    class_names=['Female', 'Male'],
    rounded = True,
    filled = True
)